### ISSUE TITLE
Invalid JSON-LD context

### ISSUE THREAD

**Issue by Sakurann** [eclipse-dataspace-dcp/decentralized-claims-protocol#32] opened 2023-11-02 17:26 UTC
The document says
> The VPP is based on Json-Ld message types. The CS Json-Ld context is:
https://w3id.org/tractusx-trust/v0.8

but the URL does not resolve to a valid JSON-LD `@context` document. should probably resolve to something like in this file https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/M1/context.json in which case, top level domain is probably not w3id.org..?

**Comment by jimmarino** [comment] 2023-11-04 09:02
Thanks for your input. A few notes and clarifications:

1. The Json-Ld context is valid. The issue is that the context is not published at the designated URL. This is planned and will be done when we have enabled publication of the specifications as static resources (see below).
2. The file should not resolve to an untagged GitHub file resource as that would be bad practice, the content type will be set by GitHub incorrectly, and clients will run into throttling imposed by the latter.
3. We have already planned to publish the context to a static location that uses the proper content type.
4. The context URL will use `w3id.org` and redirect to the static location. This approach is a common and well-documented industry practice.
5. Publishing the context is not critical. Implementations should load contexts from a trusted cache and never resolve them over the Internet for performance and security reasons.  

I'm going to close this issue and open another to track the Json-Ld context publication.

**Closed as completed by jimmarino** 2023-11-04 09:02 UTC
